<!DOCTYPE html>
<?php if (ob_get_level() == 0) ob_start(); $front_template = Zend_Registry::get('front_template'); $is_frontend = new Eicra_Model_DbTable_Frontend(); $license = new Zend_Session_Namespace('License'); $validation_data = $license->license_data;
$locale = Eicra_Global_Variable::getSession()->sess_lang;
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$frontController = Zend_Controller_Front::getInstance();
$moduleName = $frontController->getRequest()->getModuleName();	
$controllerName = strtolower($frontController->getRequest()->getControllerName());
$actionName = strtolower($frontController->getRequest()->getActionName());

?> 
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>
<meta charset="utf-8">
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/" /> 

<link rel="shortcut icon" href="<?php $global_conf = Zend_Registry::get('global_conf'); echo $global_conf['frontend_favicon']; ?>" />

<?php 
	echo $this->headMeta(); 
	echo html_entity_decode($this->headTitle(), ENT_QUOTES ,"UTF-8"); 
?>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
$version = new Eicra_License_Version();
echo $this->partial('head/headscript.phtml');
$auth = Zend_Auth::getInstance ();
$acount_link = ($auth->hasIdentity ()) ? 'Dashboard' : 'Frontend-Login';
function showRightPanel($diff_arr = array())
{
	$show_array = array(
							array('Gallery', 'frontend', 'details'),
							array('Members', 'frontend', 'login'),
							array('B2b', 'directory', 'productslist'),
							array('B2b', 'directory', 'sellist'),
							array('B2b', 'directory', 'buylist'),
							array('B2b', 'directory', 'companylist')
						);
	$return = false;
	foreach($show_array as $s_array)
	{
		if(count(array_diff($diff_arr, $s_array)) === 0)
		{
			$return = true;
			break;
		}
	}
	return $return;
}
?>
</head>
<body>
<div id="slide-in-content">
    <div id="wrapper">
        <!-- Header Start -->
        <?php echo $this->layout()->render('header'); ob_flush(); flush(); ?>
        <!-- Header End -->
        
        <!-- Header Bottom Start-->
        <?php echo $this->layout()->render('header-bottom'); ob_flush(); flush(); ?>
        <!-- Header Bottom End-->
        
        <?php
         if($is_frontend->isFrontend())
            {	
            
        ?>
        <!-- Left SideBar Start-->
        <aside id="sidebar-left">
            <?php echo $this->partial('blocks/global/menu_category.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/b2b_content_latest.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/b2b_content_selling_featured.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/currency_exchange.phtml'); ob_flush(); flush(); ?>
        </aside>
        <!-- Left SideBar End-->
        
        <!-- Main Content Start-->
        <article id="content">
            <?php $this->ad(217); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/b2b_content_featured.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/b2b_content_selling_latest.phtml'); ob_flush(); flush(); ?>
            <!-- Content Top AD Start -->
            <div class="block-ad"><?php $this->ad(212); ob_flush(); flush(); ?></div>
            <?php echo $this->partial('blocks/global/b2b_content_buying_latest.phtml'); ob_flush(); flush(); ?>
            <!-- Content Top AD End -->
            <div class="clr"></div>
            
            <?php echo $this->partial('blocks/global/members_content_profile.phtml'); ob_flush(); flush(); ?>  
            <?php echo $this->partial('blocks/global/news_content_latest.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/ad_home_content_scrolling.phtml'); ob_flush(); flush(); ?>        
        </article>
        <!-- Main Content End -->
        
        <!-- Right SideBar Start-->
        <aside id="sidebar-right">
            <!-- Tab Start-->	          
            <div id="usual" class="usual">
                <ul>
                    <li><a class="selected" href="#tab1"><span class="lock"><?php echo $this->translator->translator('block_tab_login','', '', $front_template['theme_folder']); ?></span></a></li>
                    <li><a class="" href="#tab2"><span class="alert"><?php echo $this->translator->translator('block_tab_alert','', '', $front_template['theme_folder']); ?></span></a></li>
                </ul>
            </div>
            <div class="usual-content">
                <div style="display: block;" id="tab1"><?php echo $this->partial('blocks/global/tab_login.phtml'); ob_flush(); flush(); ?></div>
                <div style="display: none;" id="tab2"><?php echo $this->partial('blocks/global/newsletter_sidebar.phtml'); ob_flush(); flush(); ?></div>
            </div>
                    
            <script type="text/javascript">
                $("#usual ul").idTabs();
            </script>
            <div class="block-ad"><?php $this->ad(211); ob_flush(); flush(); ?></div>
            <?php //echo $this->partial('blocks/global/ad_home_sidebarRight.phtml'); ?>
            <?php echo $this->partial('blocks/global/trading_stats.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/sidebar_successStory.phtml'); ob_flush(); flush(); ?>
            <?php echo $this->partial('blocks/global/b2b_sidebar_lastmindeal.phtml'); ob_flush(); flush(); ?>
        </aside>
        <!-- Right SideBar End-->
        
        <div class="clr">
            <?php echo $this->partial('blocks/global/b2b_content_popular.phtml'); ob_flush(); flush(); ?>
        </div>
        
        <!-- Scroll Start -->
        <div class="scroling">
            <?php //echo $this->partial('blocks/global/ad_content_marquee.phtml'); ?>
        </div>
        <!-- Scroll End-->
        <?php
            }
         else
            {			
                if(($moduleName == 'B2b') && ($controllerName == 'company'  || $controllerName == 'details' ))
                {
                    $helper_path = $this->getHelpers();
                    $doc_view = $helper_path[Doctype]->view;
                    $year_of_est  =$doc_view->companyDetails['establishing_year'];
                    $company_age = date('Y') - $year_of_est;
                    $number_of_years = ( $company_age >= 1 ) ?  $company_age : null;
                    $translator = Zend_Registry::get('translator');
    
                    $imageDir = $doc_view->companyDetails['images_path'];
                    $logo_img = ($doc_view->companyDetails['profile_image_primary']) ? ($doc_view->companyDetails['profile_image_primary']) : 'avatar.png';				
                    ?>              
                    
                    <!-- Inner Layout for Company Details with Profile Start -->
                    <div id="main-container">
                        <!-- Company Header Start -->
                        <div id="header-company"> 
                            <img src="<?php echo $imageDir .'/'. $logo_img; ?>" alt="<?php echo $doc_view->companyDetails['store_name'] ?>" border="0" class="logo" height="60">
                            <span class="company-name"><?php echo strtoupper($doc_view->companyDetails['company_name']) ?> </span>
                            
                            <div class="membership-pkgs">
                                <div class="pkgs"> 
                                    <img src="<?php echo $doc_view->companyDetails['default_img_path'].'/'.$doc_view->companyDetails['package_logo'] ?>" /><?php  echo ($doc_view->companyDetails['package_name']) ? $doc_view->companyDetails['package_name'] : html_entity_decode($this->translator->translator('b2b_anonymous_member'), ENT_QUOTES, "UTF-8");?>
                                </div>
    
                                <div class="membership">
                                    <?php  echo  ($number_of_years) ? '' . $number_of_years  . '<br>' . $translator->translator('b2b_years'). '' : null ?>
                                </div>
                            </div>
                            <?php if ($doc_view->companyDetails[priority_flag]) {?>
                            <div class="trusted"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/b2b_img/trusted.png" border="0" width="50"/><br><?php  echo $doc_view->companyDetails[priority_flag]?></div>
                            <?php } ?> 
                            <div class="flag"><img src="data/adminImages/flagsImage/<?php echo $doc_view->companyDetails['country_code'] ?>.gif" border="0" alt="<?php echo $doc_view->companyDetails['country_name'] ?>" /> &nbsp; (<?php echo $doc_view->companyDetails['state'].' , '. $doc_view->companyDetails['city']?>)</div>
                            
                        </div>
                        <!-- Company Header End -->
                        
                        <!-- Company Menu Start -->
                        <?php echo $this->partial('blocks/global/menu_header_company.phtml'); ?>
                        <!-- Company Menu End -->
    
                        <?php
                            $body_content_style = (showRightPanel(array($moduleName, $controllerName, $actionName)) ) ? 'style="width:100%"' : '';
                        ?>
                        <!-- Details Page Content Start -->
                        <div id="content-details-page" <?php echo $body_content_style; ?>>                    	
                            <?php if($actionName != 'login' && $moduleName != 'Articles'){ echo $this->partial('blocks/global/breadcrumb.phtml'); } ?>
                            <?php echo $this->layout()->content ?>
                        </div>
                        <!-- Details Page Content End -->
                        <?php
                        if(!showRightPanel(array($moduleName, $controllerName, $actionName)) )
                        {
                        ?>
                        <!-- Inner Sidebar Start - Details Page -->
                        <div id="sidebar-details-page">
                            <?php echo $this->partial('blocks/global/members_sidebar_contact.phtml'); ?>
    
                        </div>
                        <!-- Inner Sidebar End - Details Page  -->
                        <?php
                        }
                        ?>
                    </div>
                    <!-- Inner Layout for Product Details or Company Profile End -->
        <?php
                }
                    
                else
                {
        ?>
                    <!-- Inner Layout Start -->
                    <div id="main-container">
                    <?php
                        $body_content_style = (showRightPanel(array($moduleName, $controllerName, $actionName)) ) ? 'style="width:100%"' : '';
                    ?>
                        <!-- Inner Content Start -->
                        <div id="content-list-page" <?php echo $body_content_style; ?>>
                            <?php if($actionName != 'login' && $moduleName != 'Articles'){ echo $this->partial('blocks/global/breadcrumb.phtml'); } ?>
                            <?php echo $this->layout()->content ?>
                        </div>
                        <!-- Inner Content End -->
                        <?php					
                        if(!showRightPanel(array($moduleName, $controllerName, $actionName)) )
                        {
                        ?>
                        <!-- Inner Sidebar Start - CategoryList -->
                        <div id="sidebar-list-page">
                            <?php echo $this->partial('blocks/global/menu_successstory.phtml'); ?>
                            <?php echo $this->partial('blocks/global/menu_tradeshow.phtml'); ?>
                            <div class="block-ad"><?php $this->ad(209); ?></div>
                            <?php echo $this->partial('blocks/global/b2b_sidebar_lastmindeal.phtml'); ?>
                            <div class="block-ad"><?php $this->ad(210); ?></div>
                            <?php //echo $this->partial('blocks/global/ad_category_sidebarSmall.phtml'); ?>
                            <?php echo $this->partial('blocks/global/latest_company.phtml'); ?>
                            <?php //echo $this->partial('blocks/global/ad_inner_sidebar.phtml'); ?>
                        </div>
                        <!-- Inner Sidebar End - CategoryList -->
                        <?php
                        }
                        ?>
                    </div>
                    <!-- Inner Layout End -->
        <?php
                }
            }
        ?>
        
        <!-- Footer Start -->
        <?php echo $this->layout()->render('footer'); ?>
        <!-- Footer End -->
    </div>
	<?php if($global_conf['payment_system'] == 'On' && $global_conf['marchent_payment_system'] == 'On'){ echo $this->partial('shopping-cart.phtml'); } ?>
</div>
<div class="go-top"><a href="#top" id="scroll-top"><?php echo $this->translator->translator('front_footer_top','', '', $front_template['theme_folder']); ?></a></div>
<?php echo $this->headScript()->setFile('application/layouts/scripts/'.$front_template['theme_folder'].'/vendor/scripts/js/scroll.js'); ?>
</body>
</html>
<?php echo $this->escape($global_conf['analytics_code']); ?>