<?php 
$front_template = Zend_Registry::get('front_template'); 
$translator = Zend_Registry::get('translator');
$frontController = Zend_Controller_Front::getInstance();
$params = $frontController->getRequest()->getParams();
?>
<script>
	$(document).ready(function() {
		$("#categories").kendoComboBox({
			placeholder: "<?php echo html_entity_decode($translator->translator('common_tree_root'), ENT_QUOTES, 'UTF-8'); ?>",
			dataTextField: "name",
			dataValueField: "id",
			text: "<?php echo ($params['category_id'] && $params['categories_input']) ? $params['categories_input'] : ''; ?>",
			value: "<?php echo ($params['category_id'] && $params['categories_input']) ? $params['category_id'] : ''; ?>",
			filter: "contains",
			autoBind: false,
			minLength: 3,
			optionLabel: "<?php echo html_entity_decode($translator->translator("common_tree_root"), ENT_QUOTES, 'UTF-8'); ?>",
			template: '# if(data.id){ if(data.b2b_images){ # <img style=\"float:left; border:1px solid \\#cccccc;\" src=\"data/frontImages/b2b/b2b_images/${data.b2b_images}\" width=\"20\" height=\"20\" alt=\"${data.name}\" title=\"${data.name}\" border=\"0\" /># } #&nbsp;&nbsp;${data.name} # } #',
			dataSource: {
				type: "json",
				schema: {
					  data:	'categories'
				  }, 
				serverFiltering: true,
				transport: {
					read: {
						type: "POST",
						dataType: "json",
						url: "<?php echo $this->url(array('module' => 'B2b','controller'=>'frontend', 'action'=> 'categories'),'adminrout', true); ?>",
					}
				}
			}
		});		
	});
	function checkData()
	{
		var combobox = $("#categories").data("kendoComboBox");		
		if(combobox)
		{
			$('#category_id').val(combobox.value());				
		}
		return true;
	}
</script>
<div class="block-search">
    <form id="shortSearchform" name="shortSearchform" method="post" action="Search-Results" onsubmit="return checkData();">
        <span class="label"><?php echo $translator->translator('block_search_title','','', $front_template['theme_folder']); ?></span>
        <input name="categories" id="categories" style="vertical-align:moddle;"/><input type="hidden" name="category_id" id="category_id" value="<?php echo ($params['category_id'] && $params['categories_input']) ? $params['category_id'] : ''; ?>" />
        <input name="keywords" type="text" class="keywords" id="keywords" value="<?php echo $params['keywords']; ?>" placeholder="<?php echo $translator->translator('block_search_placeholder','','', $front_template['theme_folder']); ?>"/>
        <input type="submit" name="short_search_btn" id="short_search_btn" value="<?php echo $translator->translator('permisson_b2b_front_search', '', 'B2b'); ?>" />
    </form>

	<a href="<?php echo $this->url(array('module' => 'B2b','controller'=>'frontend', 'action'=>'search'),'Search-Results/*', true); ?>"><?php echo $translator->translator('block_search_advanced','','', $front_template['theme_folder']); ?></a>
</div>