<?php 
$front_template = Zend_Registry::get('front_template'); 
$translator = Zend_Registry::get('translator');
?>

<div class="block">
	<div class="block-heading"><div class="symbol"><?php echo 'Product Management' ?></div></div>
    <div class="block-body">
    	<ul class="stats">
        	<li><a href="Add-Product">Add a New Group </a></li>
			<li><a href="Manage-Products">Manage Group</a></li>
    		<li><a href="Add-Product">Add a New Product</a></li>
			<li><a href="Manage-Products">Manage Products</a></li>
        </ul>
    </div>
</div>